/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import exception.MotorNoSoportadoException;
import factories.DAOFactory;
import factories.MySQL_AlumnoDAO;
import factories.MySQL_ObservacionDAO;
import static gui.JFramePassword.jInsivisiblePass;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.shape.FillRule;
import model.Alumno;
import model.Asignatura;
import model.Observacion;
import model.TMObservacion;
import model.Usuario;

/**
 *
 * @author naxho
 */
public class JFrameMensaje extends javax.swing.JFrame {

    private MySQL_ObservacionDAO ob;
    private MySQL_AlumnoDAO al;
    private String rutVar;

    /**
     * Creates new form jFrameMensaje
     */
    public JFrameMensaje() {
        try {
            initComponents();
            lblInvisibleRut.setVisible(false);
            IntranetJesusDePraga i = new IntranetJesusDePraga();
            lblInvisibleRut.setText(i.rut);
//            System.out.println("MSJ"+ lblInvisibleRut.getText());
            
            al = new MySQL_AlumnoDAO();
            
            ob = new MySQL_ObservacionDAO();
            cargarASignatura();
//            cargarTablaObservacion();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrameMensaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMensaje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_alumno1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_anotacionALumno = new javax.swing.JLabel();
        btn_atrasMensaje = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabObservacion = new javax.swing.JTable();
        txFObserva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblInvisibleRut = new javax.swing.JLabel();
        cboAsignatura = new javax.swing.JComboBox();
        btnAsignatura = new javax.swing.JButton();

        jLabel2.setText("Favor de seleccionar asignatura :");

        lbl_alumno1.setText("X");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anotaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        lbl_anotacionALumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_anotacionALumno.setText("Asignatura:");

        btn_atrasMensaje.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_atrasMensaje.setText("Atrás");
        btn_atrasMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasMensajeActionPerformed(evt);
            }
        });

        tabObservacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabObservacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabObservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabObservacionMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabObservacion);

        txFObserva.setEditable(false);
        txFObserva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txFObserva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFObserva.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/examen(1).png"))); // NOI18N

        cboAsignatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        cboAsignatura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAsignatura.setText("Seleccionar");
        btnAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFObserva, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_anotacionALumno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btn_atrasMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInvisibleRut)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_anotacionALumno)
                        .addComponent(cboAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAsignatura)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txFObserva, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_atrasMensaje)
                    .addComponent(lblInvisibleRut))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasMensajeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_atrasMensajeActionPerformed

    private void tabObservacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabObservacionMouseReleased
        if (evt.getClickCount() == 2) {
            int fila = tabObservacion.getSelectedRow();
            System.out.println(fila);
            TMObservacion tabla = (TMObservacion) tabObservacion.getModel();

            Observacion o = tabla.getObservacion(fila);
            Alumno a;
            a = al.getByID(o.getAlumno());

            txFObserva.setText(o.getObservacion());
        }
    }//GEN-LAST:event_tabObservacionMouseReleased

    private void btnAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignaturaActionPerformed
       cargarTablaObservacion();
    }//GEN-LAST:event_btnAsignaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMensaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignatura;
    private javax.swing.JButton btn_atrasMensaje;
    private javax.swing.JComboBox cboAsignatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblInvisibleRut;
    private javax.swing.JLabel lbl_alumno1;
    private javax.swing.JLabel lbl_anotacionALumno;
    private javax.swing.JTable tabObservacion;
    private javax.swing.JTextField txFObserva;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaObservacion() {

        try {
            String valor = lblInvisibleRut.getText();
            Asignatura a = (Asignatura) cboAsignatura.getSelectedItem();
            List<Observacion> list = ob.getByRut(valor,String.valueOf(a.getId()));
            TMObservacion tm;

            tm = new TMObservacion(list);
            tabObservacion.setModel(tm);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrameMensaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMensaje.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void cargarASignatura(){
    try {
//            String rut = jInvisibleCrearAsig.getText();
//            user = DAOFactory.getInstance().getUsuarioDAO(DAOFactory.Motor.MY_SQL).search(rut).get(0);
            List<Asignatura> listAsig = DAOFactory.getInstance().getAsignaturaDAO(DAOFactory.Motor.MY_SQL).read();
            cboAsignatura.removeAllItems();
            for (Asignatura a : listAsig) {
                cboAsignatura.addItem(a);
            }

        } catch (MotorNoSoportadoException ex) {
            Logger.getLogger(JFrameSubirNota.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrameSubirNota.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameSubirNota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
